# Generated by Django 4.2.8 on 2023-12-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('difficulty_rating', models.CharField(max_length=50)),
                ('description_details', models.TextField()),
            ],
        ),
    ]
